apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 730335429934.dkr.ecr.us-east-1.amazonaws.com/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        
        # --- CONFIGURACIÓN DE PROBES (Auto Healing / Criterio Evaluación) ---
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5

        # --- RECURSOS (Requisito para métricas y escalabilidad) ---
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"

        # --- VARIABLES DE ENTORNO SEGURAS (Criterio Secrets) ---
        env:
        - name: PORT
          value: "3001"
        - name: DB_HOST
          value: "db-service"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tienda-db-secrets
              key: mysql-root-password
        - name: DB_NAME
          value: "tienda_perritos"
        - name: DB_PORT
          value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - name: http
    port: 8001
    targetPort: 3001
