name: CI/CD Tienda Perritos - DB

on:
  push:
    branches: [ "main" ]
    paths:
      - "db/**"
      - "k8s/db-deployment.yaml"
      - "k8s/tienda-secrets.yaml"

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (runner)
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen DB y push a ECR
      run: |
        cd db
        docker build -t tienda-db .
        docker tag tienda-db:latest ${{ secrets.ECR_REPO_URL_DB }}:latest
        docker push ${{ secrets.ECR_REPO_URL_DB }}:latest

    - name: Configurar Kubeconfig para EKS
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Desplegar en EKS
      run: |
        # 1. Aplicar la definición de Secrets de base de datos
        kubectl apply -f k8s/tienda-secrets.yaml
        # 2. Aplicar el despliegue de base de datos protegido
        kubectl apply -f k8s/db-deployment.yaml
        # 3. Reiniciar ordenadamente para reflejar cambios e imágenes frescas
        kubectl rollout restart deployment/db-deployment
