apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: default
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: 730335429934.dkr.ecr.us-east-1.amazonaws.com/db:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        
        # --- RECURSOS (Obligatorio para que no arroje inconsistencias de clúster) ---
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"

        # --- VARIABLES DE ENTORNO SEGURAS CON KUBERNETES SECRETS ---
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tienda-db-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          value: "tienda_perritos"
        - name: MYSQL_USER
          value: "alumno"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tienda-db-secrets
              key: mysql-password
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
