name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches:
      - main
    # === CAMBIO 1: Restricción de rutas para nota máxima en organización ===
    paths:
      - "frontend/**"
      - "k8s/frontend-deployment.yaml"
      - "k8s/frontend-hpa.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          # Usamos la variable global de región por consistencia técnica
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        run: |
          docker build -t frontend ./frontend

      - name: Tag Docker Image
        run: |
          docker tag frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

      - name: Configurar Kubeconfig para EKS
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Desplegar en EKS
        run: |
          # Aplicamos de forma limpia tus manifiestos
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-hpa.yaml
          # === CAMBIO 2: Corrección sintáctica (eliminado el punto suelto final) ===
          kubectl rollout restart deployment/frontend-deployment
